sonar.organization=republique-et-canton-de-geneve
sonar.projectKey=republique-et-canton-de-geneve_noms-geographiques
sonar.projectName=noms-geographiques
sonar.exclusions=htdocs/libraries/**,htdocs/themes/custom/gech_app/src/fontawesome/**,htdocs/themes/custom/gech_app/src/scss/**
